version: '3.7'

services:

    app:
        build: monitoring
        ports:
            - 8080:8080
        networks:
            monitoring:
                aliases:
                    - app

    grafana:
        build: './grafana'
        ports:
            - 3000:3000
        volumes:
            - ./grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
        networks:
            monitoring:
                aliases:
                    - grafana

    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus:/prometheus
        networks:
            monitoring:
                aliases:
                    - prometheus
networks:
    monitoring:
